import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,useLocation,useNavigate,useParams,Link} from 'react-router-dom';
import * as Icons from 'lucide-react';
import './styles.css';

const COURSES=[
['Mecânica Industrial','Mecânica','⚙️'],['Soldadura Industrial (SMAW)','Soldadura','🔥'],['Soldadura TIG','Soldadura','◈'],['Eletricidade Industrial','Eletricidade','⚡'],['Soldadura MIG/MAG','Soldadura','✦'],['Tubagem Industrial','Tubagem','◌'],['Instalações Hidráulicas','Hidráulica','◍'],['Automação Industrial','Automação','🤖'],['Eletricidade de Baixa Tensão','Eletricidade','⌁'],['AVAC e Frio Industrial','AVAC','❄️'],['Escavadeira Giratória','Máquinas Pesadas','▣'],['Grua Móvel','Máquinas Pesadas','🏗️'],['Retroescavadeira','Máquinas Pesadas','▰'],['Empilhadeira','Máquinas Pesadas','▥'],['Instrumentação e Controle Industrial','Automação','◉'],['BST (Basic Safety Training)','Segurança','🛡️'],['Desenho Técnico','CAD / Desenho','⌗'],['AutoCAD','CAD / Desenho','▦'],['Francês','Idiomas','FR'],['Inglês','Idiomas','EN'],['PLC','Automação','PLC']
].map((x,i)=>({id:i+1,name:x[0],category:x[1],icon:x[2],status:'published',duration:'A confirmar',price:'A confirmar'}));
const initialNews=[{id:1,title:'Inscrições abertas para novas turmas',date:'2026-09-22',status:'published',text:'Garanta a sua vaga nas formações disponíveis.'}];
const KEY='industel_admin_v1';
function getStore(){try{return JSON.parse(localStorage.getItem(KEY))||{courses:COURSES,news:initialNews,applications:[],messages:[]}}catch{return {courses:COURSES,news:initialNews,applications:[],messages:[]}}}
function saveStore(s){localStorage.setItem(KEY,JSON.stringify(s));}

function Logo(){return <Link className="logo" to="/"><span className="logoMark"><span>IH</span></span><span><b>INDUSTEL</b><small>EXCELÊNCIA PROFISSIONAL</small></span></Link>}
function Scene3D(){return <div className="scene3d" aria-hidden="true"><div className="orb orbA"/><div className="orb orbB"/><div className="gridFloor"/><div className="ring r1"/><div className="ring r2"/><div className="cube"><i/><i/><i/><i/><i/><i/></div><div className="scanline"/></div>}
function WhatsApp(){return <a className="whatsapp" href="https://wa.me/244923035999" target="_blank" rel="noreferrer"><Icons.MessageCircle size={20}/> WhatsApp</a>}
function Layout({children}){const [open,setOpen]=useState(false);return <><header><Logo/><button className="menuBtn" onClick={()=>setOpen(!open)} aria-label="Abrir menu"><Icons.Menu/></button><nav className={open?'open':''}><Link to="/" onClick={()=>setOpen(false)}>Início</Link><Link to="/cursos" onClick={()=>setOpen(false)}>Cursos</Link><Link to="/academia" onClick={()=>setOpen(false)}>Academia</Link><Link to="/sobre" onClick={()=>setOpen(false)}>Sobre</Link><Link to="/noticias" onClick={()=>setOpen(false)}>Notícias</Link><Link to="/contactos" onClick={()=>setOpen(false)}>Contactos</Link><Link className="navCta" to="/inscricao">Inscrever-me</Link></nav></header>{children}<WhatsApp/><footer><Logo/><span>© {new Date().getFullYear()} INDUSTEL · Luanda, Angola</span><Link to="/admin/login">Área administrativa</Link></footer></>}
function Home(){return <Layout><main><section className="hero"><Scene3D/><div className="heroContent"><p className="eyebrow">ACADEMIA DE FORMAÇÃO INDUSTRIAL · ANGOLA</p><h1>Excelência profissional para o <em>futuro industrial.</em></h1><p className="lead">Formação técnica e industrial orientada para conhecimento, prática e desenvolvimento profissional.</p><div className="actions"><Link className="btn primary" to="/cursos">Explorar cursos <Icons.ArrowUpRight/></Link><Link className="btn ghost" to="/inscricao">Quero inscrever-me</Link></div><div className="heroStats"><span><b>21</b><small>formações identificadas</small></span><span><b>Luanda</b><small>Vila de Cacuaco</small></span><span><b>INEFOP</b><small>certificação referida no material</small></span></div></div></section><section className="section intro"><div><p className="eyebrow">INDUSTEL</p><h2>Conhecimento técnico. <span>Visão industrial.</span></h2></div><p>Uma presença digital criada para apresentar a formação da INDUSTEL com uma linguagem visual tecnológica, clara e preparada para crescer.</p></section><section className="section"><div className="sectionHead"><div><p className="eyebrow">FORMAÇÃO</p><h2>Áreas em destaque</h2></div><Link to="/cursos">Ver todas <Icons.ArrowRight/></Link></div><div className="courseGrid">{COURSES.slice(0,8).map(c=><CourseCard key={c.id} c={c}/>)}</div></section><section className="section manifesto"><div className="manifestoCard"><p className="eyebrow">O PRÓXIMO PASSO</p><h2>Transforme conhecimento em <span>prática.</span></h2><p>Escolha a formação, consulte os detalhes disponíveis e envie o seu pedido de inscrição.</p><Link className="btn primary" to="/inscricao">Começar inscrição <Icons.ArrowUpRight/></Link></div></section></main></Layout>}
function CourseCard({c}){return <Link className="courseCard" to={'/cursos/'+c.id}><div className="courseIcon">{c.icon}</div><span>{c.category}</span><h3>{c.name}</h3><small>Detalhes da formação <Icons.ArrowUpRight size={15}/></small></Link>}
function Courses(){const [q,setQ]=useState('');const [cat,setCat]=useState('Todas');const cats=['Todas',...new Set(COURSES.map(c=>c.category))];const list=COURSES.filter(c=>(cat==='Todas'||c.category===cat)&&c.name.toLowerCase().includes(q.toLowerCase()));return <Layout><main className="page"><div className="pageHero"><p className="eyebrow">CATÁLOGO DE FORMAÇÃO</p><h1>Escolha a sua próxima <em>especialização.</em></h1><p>Explore as formações industriais identificadas para a INDUSTEL.</p></div><div className="filters"><div className="search"><Icons.Search/><input placeholder="Pesquisar curso..." value={q} onChange={e=>setQ(e.target.value)}/></div><select value={cat} onChange={e=>setCat(e.target.value)}>{cats.map(x=><option key={x}>{x}</option>)}</select></div><div className="courseGrid">{list.map(c=><CourseCard key={c.id} c={c}/>)}</div></main></Layout>}
function CourseDetail(){const {id}=useParams();const c=COURSES.find(x=>x.id===Number(id));if(!c)return <Layout><main className="page"><h1>Curso não encontrado</h1><Link to="/cursos">Voltar aos cursos</Link></main></Layout>;return <Layout><main className="detail"><div className="detailVisual"><Scene3D/><div className="detailIcon">{c.icon}</div></div><div className="detailBody"><p className="eyebrow">{c.category}</p><h1>{c.name}</h1><p>Formação disponível no catálogo da INDUSTEL. Os dados de duração, preço, horário e requisitos serão apresentados quando forem confirmados pela administração.</p><div className="infoGrid"><div><b>Duração</b><span>{c.duration}</span></div><div><b>Preço</b><span>{c.price}</span></div><div><b>Modalidade</b><span>Presencial</span></div><div><b>Certificação</b><span>A confirmar</span></div></div><Link className="btn primary" to={'/inscricao?curso='+c.id}>Tenho interesse <Icons.ArrowUpRight/></Link></div></main></Layout>}
function Inscricao(){const [s,setS]=useState({name:'',phone:'',email:'',course:'',message:''});const [ok,setOk]=useState(false);function submit(e){e.preventDefault();if(!s.name||!s.phone||!s.course)return;const st=getStore();st.applications.unshift({...s,id:Date.now(),status:'nova',createdAt:new Date().toISOString()});saveStore(st);setOk(true);setS({name:'',phone:'',email:'',course:'',message:''});}return <Layout><main className="formPage"><div><p className="eyebrow">INSCRIÇÃO</p><h1>O seu próximo passo começa aqui.</h1><p>Envie os seus dados. A equipa poderá entrar em contacto para confirmar as informações da formação.</p></div><form onSubmit={submit} className="formCard">{ok&&<div className="success">Pedido enviado com sucesso.</div>}<label>Nome completo<input value={s.name} onChange={e=>setS({...s,name:e.target.value})} required/></label><label>Telefone / WhatsApp<input value={s.phone} onChange={e=>setS({...s,phone:e.target.value})} required/></label><label>Email <small>(opcional)</small><input type="email" value={s.email} onChange={e=>setS({...s,email:e.target.value})}/></label><label>Curso<select value={s.course} onChange={e=>setS({...s,course:e.target.value})} required><option value="">Selecionar</option>{COURSES.map(c=><option key={c.id} value={c.name}>{c.name}</option>)}</select></label><label>Mensagem<textarea rows="5" value={s.message} onChange={e=>setS({...s,message:e.target.value})}/></label><button className="btn primary" type="submit">Enviar inscrição <Icons.Send/></button></form></main></Layout>}
function SimplePage({title,eyebrow,children}){return <Layout><main className="page"><div className="pageHero"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{children}</div></main></Layout>}
function News(){const st=getStore();return <Layout><main className="page"><div className="pageHero"><p className="eyebrow">ATUALIZAÇÕES</p><h1>Notícias da INDUSTEL</h1></div><div className="newsGrid">{st.news.map(n=><article className="newsCard" key={n.id}><span>{n.date}</span><h2>{n.title}</h2><p>{n.text}</p></article>)}</div></main></Layout>}
function Contacts(){return <SimplePage eyebrow="CONTACTOS" title="Fale com a INDUSTEL"><div className="contactGrid"><a href="tel:+244923035999"><Icons.Phone/>923 035 999</a><a href="mailto:info@industel.ao"><Icons.Mail/>info@industel.ao</a><a href="https://wa.me/244923035999"><Icons.MessageCircle/>+244 923 035 999</a><div><Icons.MapPin/>Vila de Cacuaco, Luanda, Angola</div></div><p className="note">O endereço completo ainda não foi confirmado. Não mostramos um mapa preciso até essa informação ser validada.</p></SimplePage>}
function Academia(){return <SimplePage eyebrow="ACADEMIA" title="Formação industrial com visão de futuro."><p>A INDUSTEL apresenta formação presencial em áreas técnicas e industriais. O material fornecido também informa salas climatizadas, formadores capacitados e certificados reconhecidos pelo INEFOP.</p></SimplePage>}
function Sobre(){return <SimplePage eyebrow="SOBRE A INDUSTEL" title="Excelência Profissional."><p>Esta primeira versão não inventa uma história institucional. O conteúdo oficial de missão, visão, valores e história poderá ser preenchido no painel administrativo assim que for fornecido pela empresa.</p></SimplePage>}

function AdminLogin(){const nav=useNavigate();const [email,setEmail]=useState('admin@industel.ao');const [pw,setPw]=useState('');const [err,setErr]=useState('');function login(e){e.preventDefault();if(email&&pw){localStorage.setItem('industel_session',JSON.stringify({email,role:'super_admin'}));nav('/admin');}else setErr('Preencha os campos.')}return <main className="adminLogin"><div className="loginBox"><Logo/><p className="eyebrow">ÁREA ADMINISTRATIVA</p><h1>Entrar no painel</h1><p className="muted">Protótipo local. A autenticação Supabase será ligada na fase de produção.</p><form onSubmit={login}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Palavra-passe<input type="password" value={pw} onChange={e=>setPw(e.target.value)} placeholder="••••••••"/></label>{err&&<div className="error">{err}</div>}<button className="btn primary">Entrar</button></form></div></main>}
function Admin(){const nav=useNavigate();const [tab,setTab]=useState('Dashboard');const [store,setStore]=useState(getStore());const [courseName,setCourseName]=useState('');useEffect(()=>{if(!localStorage.getItem('industel_session'))nav('/admin/login')},[]);function logout(){localStorage.removeItem('industel_session');nav('/admin/login')}function addCourse(e){e.preventDefault();if(!courseName)return;const ns={...store,courses:[...store.courses,{id:Date.now(),name:courseName,category:'A confirmar',icon:'◈',status:'draft',duration:'A confirmar',price:'A confirmar'}]};setStore(ns);saveStore(ns);setCourseName('')}const menu=['Dashboard','Cursos','Inscrições','Notícias','Galeria','Páginas','Configurações','Utilizadores','Auditoria'];return <div className="admin"><aside><Logo/><div className="adminMenu">{menu.map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div><button className="logout" onClick={logout}>Sair</button></aside><section className="adminMain"><div className="adminTop"><div><p className="eyebrow">ADMINISTRADOR</p><h1>{tab}</h1></div><span className="role">SUPER ADMIN</span></div>{tab==='Dashboard'&&<Dashboard store={store}/>} {tab==='Cursos'&&<div><div className="statRow"><div className="adminCard"><b>{store.courses.length}</b><span>cursos no catálogo</span></div><div className="adminCard"><b>{store.courses.filter(x=>x.status==='published').length}</b><span>publicados</span></div></div><form className="inlineForm" onSubmit={addCourse}><input placeholder="Nome do novo curso" value={courseName} onChange={e=>setCourseName(e.target.value)}/><button className="btn primary">Adicionar</button></form><div className="table">{store.courses.map(c=><div className="tr" key={c.id}><span>{c.name}</span><small>{c.category}</small><em>{c.status}</em></div>)}</div></div>}{tab==='Inscrições'&&<div className="table">{store.applications.length?store.applications.map(a=><div className="tr" key={a.id}><span>{a.name}<small>{a.phone}</small></span><small>{a.course}</small><em>{a.status}</em></div>):<Empty text="Ainda não existem inscrições."/>}</div>}{tab==='Notícias'&&<div className="table">{store.news.map(n=><div className="tr" key={n.id}><span>{n.title}</span><small>{n.date}</small><em>{n.status}</em></div>)}</div>}{['Galeria','Páginas','Configurações','Utilizadores','Auditoria'].includes(tab)&&<Empty text={tab==='Configurações'?'Área preparada para dados de contacto, redes sociais, SEO e conteúdo editável.':`Módulo ${tab.toLowerCase()} preparado para ligação ao Supabase.`}/>}</section></div>}
function Dashboard({store}){return <div><div className="statRow"><div className="adminCard"><b>{store.courses.length}</b><span>Cursos</span></div><div className="adminCard"><b>{store.applications.length}</b><span>Inscrições</span></div><div className="adminCard"><b>{store.news.length}</b><span>Notícias</span></div><div className="adminCard"><b>{store.messages.length}</b><span>Mensagens</span></div></div><div className="adminPanel"><h2>Estado do sistema</h2><p>Frontend, navegação, catálogo e fluxo de inscrição ativos localmente.</p><p className="warning">Produção: ligar Supabase Auth + RLS antes de aceitar dados reais.</p></div></div>}
function Empty({text}){return <div className="empty"><Icons.Database/><h2>{text}</h2><p>Este módulo faz parte da arquitetura administrativa da primeira versão.</p></div>}
function App(){const path=useLocation().pathname;if(path==='/admin/login')return <AdminLogin/>;if(path==='/admin'||path.startsWith('/admin/'))return <Admin/>;if(path==='/cursos')return <Courses/>;if(path.startsWith('/cursos/'))return <CourseDetail/>;if(path==='/inscricao')return <Inscricao/>;if(path==='/noticias')return <News/>;if(path==='/contactos')return <Contacts/>;if(path==='/academia')return <Academia/>;if(path==='/sobre')return <Sobre/>;return <Home/>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
